### ISSUE TITLE
xochitl 2.5.0.27 No longer picking up the new image after download

### ISSUE THREAD

**Issue by Snowflake6** [Evidlo/remarkable_news#25] opened 2020-12-09 22:37 UTC
Seems something may have changed with the 2.5.0.27 update that I received this morning.  I use the Lorem option, but it seems the image, while it's being downloaded, will not change until the reMarkable is rebooted.  Log showing correct download behaviour:

> Dec 09 14:31:47 reMarkable systemd[1]: Stopping Picsum...
> Dec 09 14:31:47 reMarkable systemd[1]: Stopped Picsum.
> Dec 09 14:31:53 reMarkable systemd[1]: Started Picsum.
Dec 09 14:32:05 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"off"] []]]
Dec 09 14:32:13 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"no-carrier"] []]]
Dec 09 14:32:18 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"dormant"] []]]
Dec 09 14:32:18 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"carrier"] []]]
Dec 09 14:32:19 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"degraded"] []]]
Dec 09 14:32:24 reMarkable renews.arm[741]: [dbus message: [org.freedesktop.network1.Link map[OperationalState:"routable"] []]]
Dec 09 14:32:24 reMarkable renews.arm[741]: [Network online]
Dec 09 14:32:30 reMarkable renews.arm[741]: [Beginning download]
Dec 09 14:32:33 reMarkable renews.arm[741]: [Adjusting image]
Dec 09 14:32:37 reMarkable renews.arm[741]: [Image saved to  /usr/share/remarkable/suspended.png]

But the suspended.png file downloaded is not the one displayed... The last one downloaded before a reboot is the one displayed.

**Comment by harrylepotter** [comment] 2020-12-10 01:53
seems like xichtl is not using /usr/share/remarkable/suspended.png anymore :-(

**Comment by motusRP** [comment] 2020-12-10 02:44
It is using it somewhere, as it picks the image up after a reboot.  So it must be getting cached somewhere.

**Comment by fringley** [comment] 2020-12-17 23:20
I'm seeing a totally new file - splash.png?  I've tried overwriting this too - but also doesn't seem to display...

Theres also a splash.dat file there which I don't remember seeing before.  Is it possible that this dat file is now used to create the suspend screen on the fly?

**Comment by fringley** [comment] 2020-12-18 00:03
After a bit more testing (rM2), I'm seeing the same behaviour.  The updated suspended.png is displaying in sleep after a reboot.

**Comment by harrylepotter** [comment] 2020-12-18 00:29
Likely the only solution here would involve copying the image contents into xochitl’s memory map, which is likely a massive PITA and would involve some seriously heavy lifting

**Comment by Snowflake6** [comment] 2020-12-18 00:31
Unless there's a way to force xochitl to re-cache the image.

**Comment by AdeelK93** [comment] 2020-12-31 22:13
As @lgnap noted in the other thread, `systemctl restart xochitl.service` works reliably well. Would there perhaps be a way to trigger an early morning scheduled restart of xochitl, after the image is refreshed?

**Comment by harrylepotter** [comment] 2020-12-31 22:48
i did a bit of fishing around using strace on xochitl to see what it does on suspend. You could potentially listen in on ~/home/root/.cache/remarkable/xochitl/telemetry/* for an 'end' file potentially, and push an image to the framebuffer... It seems theres a few seconds between the image going to the framebuffer, and /sys/power/state getting written to..
@AdeelK93 's solution might be more straightforward though

**Comment by Snowflake6** [comment] 2021-01-04 19:19
> As @lgnap noted in the other thread, `systemctl restart xochitl.service` works reliably well. Would there perhaps be a way to trigger an early morning scheduled restart of xochitl, after the image is refreshed?

This isn't really much of a solution... remarkable_news triggers when you wake it from sleep and wifi connects.  So you'd wake it up, renews runs and gets a new image, and then forces xochitl to reboot.  And when it reboots it connects to wifi, and then tries to download again.

Also, systemctl restart xochitl.service kicks you out of toltec/oxide if you use it, which isn't ideal either.

**Comment by AdeelK93** [comment] 2021-01-04 20:41
Thanks for the clarification @Snowflake6, I was not aware that that is how `remarkable_news` works

**Comment by Evidlo** [comment] 2021-01-07 18:45
I'm guessing this also breaks https://github.com/Neurone/reMarkable.

**Comment by Evidlo** [comment] 2021-01-07 18:51
I encourage people to reach out to reMarkable: https://support.remarkable.com/hc/en-us/requests/new?ticket_form_id=360000010097

Use the subject `suspended.png not being reloaded with xochitl 2.5.0.27`, explain the problem and include a link to this issue.

**Comment by motusRP** [comment] 2021-01-07 19:06
There's no reason for reMarkable to address this however... They're not expected to support hacking the rM.

**Comment by Snowflake6** [comment] 2021-01-07 19:13
@Evidlo Do you know what the "Receiver Contact Name" field should be on the remarkable request form?  It's got an asterisk next to it so it wants something there...

**Comment by pjrwees** [comment] 2021-02-19 08:01
ddvk fixed this in patch [17.2.05](https://github.com/ddvk/remarkable-hacks/tree/master/patches/25027_rm2) of rmhacks.

**Comment by Snowflake6** [comment] 2021-02-22 17:07
> ddvk fixed this in patch [17.2.05](https://github.com/ddvk/remarkable-hacks/tree/master/patches/25027_rm2) of rmhacks.

I guess we'll have to wait for that to make it to a release.  It's in the rm2 patch folder, will that affect whether it rolls to rm1 users?

**Comment by OldhamMade** [comment] 2021-05-17 12:39
It would be great to have the image auto-update without having to install rmhacks. I've sent a support request to the rM team as outlined above. Hopefully there will be a resolution soon.

**Comment by Axenntio** [comment] 2023-07-10 14:01
Looks like in software version 3.5, there is no cache anymore on the `suspend.png` file.

**Comment by Evidlo** [comment] 2023-07-25 18:20
@Axenntio That's good news!  I'll close this if someone else can confirm.

**Comment by hashworks** [comment] 2023-12-17 17:58
I can confirm that on 3.9 a xochitl restart is not required.

**Closed** 2024-01-31 00:38 UTC
